import json
import os
from subprocess import run
from customize_authorization import config


def get_oauth_token():
    """
    Generate a bearer token for a user profile on a SAS Viya services node.

    :return: oath_token: a bearer token
    """

    # Authenticate via the sas-admin CLI:
    username = os.getenv("VIYA_USERNAME")
    password = os.getenv("VIYA_PASSWORD")
    cli_command = f"sas-admin --quiet --sas-endpoint {config.BASE_URL} authenticate login -u {username} -p {password}"
    auth_result = run(cli_command)
    if auth_result.returncode == 1:
        raise ValueError("Authentication failed, please ensure that you have set the VIYA_USERNAME and VIYA_PASSWORD \
                         environment variables. Also verify the value of config.BASE_URL and/or the value of the \
                         --sas-endpoint parameter.")

    # Ingest the credentials.json file generated by the sas-admin CLI:
    with open(config.CREDENTIALS_PATH, "r") as f:
        data = json.loads(f.read())

    # Extract the bearer token generated by the sas-admin CLI and return it:
    oauth_token = f"bearer {data['Default']['access-token']}"
    return oauth_token
